# Data Auditing & Cleaning Phase

In [403]:
import pandas as pd
import numpy as np

In [404]:
df = pd.read_csv("./data/Leads.csv")
df.head(10)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
5,2058ef08-2858-443e-a01f-a9237db2f5ce,660680,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,NaN,NaN,01.High,02.Medium,17.0,15.0,No,No,Modified
6,9fae7df4-169d-489b-afe4-0f3d752542ed,660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,No,Modified
7,20ef72a2-fb3b-45e0-924e-551c5fa59095,660664,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Modified
8,cfa0128c-a0da-4656-9d47-0aa4e67bf690,660624,Landing Page Submission,Direct Traffic,No,No,0,2.0,71,2.0,...,No,NaN,Thane & Outskirts,02.Medium,02.Medium,14.0,14.0,No,Yes,Email Opened
9,af465dfc-7204-4130-9e05-33231863c4b5,660616,API,Google,No,No,0,4.0,58,4.0,...,No,NaN,Mumbai,02.Medium,02.Medium,13.0,16.0,No,No,Email Opened

**Replacing null placeholders with null**

In [405]:
df = df.replace("Select",np.nan)
df.head(10)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,NaN,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,NaN,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
5,2058ef08-2858-443e-a01f-a9237db2f5ce,660680,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,NaN,NaN,01.High,02.Medium,17.0,15.0,No,No,Modified
6,9fae7df4-169d-489b-afe4-0f3d752542ed,660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,No,Modified
7,20ef72a2-fb3b-45e0-924e-551c5fa59095,660664,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Modified
8,cfa0128c-a0da-4656-9d47-0aa4e67bf690,660624,Landing Page Submission,Direct Traffic,No,No,0,2.0,71,2.0,...,No,NaN,Thane & Outskirts,02.Medium,02.Medium,14.0,14.0,No,Yes,Email Opened
9,af465dfc-7204-4130-9e05-33231863c4b5,660616,API,Google,No,No,0,4.0,58,4.0,...,No,NaN,Mumbai,02.Medium,02.Medium,13.0,16.0,No,No,Email Opened

In [406]:
df.isnull().sum().sort_values(ascending=False)

How did you hear about X Education               7250
Lead Profile                                     6855
Lead Quality                                     4767
Asymmetrique Profile Index                       4218
Asymmetrique Activity Index                      4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Score                       4218
City                                             3669
Specialization                                   3380
Tags                                             3353
What matters most to you in choosing a course    2709
What is your current occupation                  2690
Country                                          2461
Page Views Per Visit                              137
TotalVisits                                       137
Last Activity                                     103
Lead Source                                        36
Do Not Email                                        0
Lead Origin                                         0
Lead Number                                         0
Prospect ID                                         0
Newspaper                                           0
X Education Forums                                  0
Newspaper Article                                   0
Magazine                                            0
Search                                              0
Total Time Spent on Website                         0
Do Not Call                                         0
Converted                                           0
Get updates on DM Content                           0
Update me on Supply Chain Content                   0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Digital Advertisement                               0
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

## Dataset Summary

The results below suggest that :-
- Columns with missing values greater than 50% should be removed as filling them would basically be generating new data.
- Columns with previous index and score whould also be removed to avoid data leakage.
- Columns with high cardinality such as IDs should be removed or adjusted for one hot encoding.
- Missing values should be replaced with appropriate placeholder values.

**Checking the rate of missing values to understand which columns to remove and which columns to modify**

In [407]:
def missing_values(df):
    missing_rate = df.isnull().mean().round(4).sort_values(ascending=False)*100
    return missing_rate

missing_values(df)

How did you hear about X Education               78.46
Lead Profile                                     74.19
Lead Quality                                     51.59
Asymmetrique Profile Index                       45.65
Asymmetrique Activity Index                      45.65
Asymmetrique Activity Score                      45.65
Asymmetrique Profile Score                       45.65
City                                             39.71
Specialization                                   36.58
Tags                                             36.29
What matters most to you in choosing a course    29.32
What is your current occupation                  29.11
Country                                          26.63
Page Views Per Visit                              1.48
TotalVisits                                       1.48
Last Activity                                     1.11
Lead Source                                       0.39
Do Not Email                                      0.00
Lead Origin                                       0.00
Lead Number                                       0.00
Prospect ID                                       0.00
Newspaper                                         0.00
X Education Forums                                0.00
Newspaper Article                                 0.00
Magazine                                          0.00
Search                                            0.00
Total Time Spent on Website                       0.00
Do Not Call                                       0.00
Converted                                         0.00
Get updates on DM Content                         0.00
Update me on Supply Chain Content                 0.00
Through Recommendations                           0.00
Receive More Updates About Our Courses            0.00
Digital Advertisement                             0.00
I agree to pay the amount through cheque          0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

**Checking unique values to remove/adjust high cardinality columns for one hot encoding**

In [408]:
def check_unique_values(df):
    unique_values = df.select_dtypes("object").nunique().sort_values(ascending=False)
    return unique_values

check_unique_values(df)

C:\Users\Tonmoy Saha\AppData\Local\Temp\ipykernel_44328\4039606583.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  unique_values = df.select_dtypes("object").nunique().sort_values(ascending=False)

Prospect ID                                      9240
Country                                            38
Tags                                               26
Lead Source                                        21
Specialization                                     18
Last Activity                                      17
Last Notable Activity                              16
How did you hear about X Education                  9
What is your current occupation                     6
City                                                6
Lead Quality                                        5
Lead Origin                                         5
Lead Profile                                        5
What matters most to you in choosing a course       3
Asymmetrique Profile Index                          3
Asymmetrique Activity Index                         3
Newspaper                                           2
Do Not Call                                         2
Do Not Email                                        2
Newspaper Article                                   2
Search                                              2
X Education Forums                                  2
Digital Advertisement                               2
A free copy of Mastering The Interview              2
Through Recommendations                             2
Magazine                                            1
Update me on Supply Chain Content                   1
Receive More Updates About Our Courses              1
Get updates on DM Content                           1
I agree to pay the amount through cheque            1
dtype: int64

**Checking if the target column is well balanced for training**

In [409]:
def target_column_distribution(df):
    target_normalization = df["Converted"].value_counts(normalize=True)
    return target_normalization

target_column_distribution(df)

Converted
0    0.61461
1    0.38539
Name: proportion, dtype: float64

## Data Cleaning

**Dropping the straighforward unnecessary columns (Include IDs, Unnecessary Info, Redundent Info)**

In [410]:
drop_list = ["Lead Quality","Lead Profile","How did you hear about X Education","Asymmetrique Activity Index", "Last Notable Activity",
             "Asymmetrique Profile Index","Asymmetrique Activity Score","Asymmetrique Profile Score","Prospect ID"]
df.drop(drop_list,axis=1,inplace=True)
df.head(5)

,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,...,Newspaper,Digital Advertisement,Through Recommendations,Receive More Updates About Our Courses,Tags,Update me on Supply Chain Content,Get updates on DM Content,City,I agree to pay the amount through cheque,A free copy of Mastering The Interview
0,660737,API,Olark Chat,No,No,0,0.0,0,0.0,Page Visited on Website,...,No,No,No,No,Interested in other courses,No,No,NaN,No,No
1,660728,API,Organic Search,No,No,0,5.0,674,2.5,Email Opened,...,No,No,No,No,Ringing,No,No,NaN,No,No
2,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,Email Opened,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,Yes
3,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,Unreachable,...,No,No,No,No,Ringing,No,No,Mumbai,No,No
4,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,Converted to Lead,...,No,No,No,No,Will revert after reading the email,No,No,Mumbai,No,No

**Changing the null values for categorical data to "Unknown" and the median value for numeric data.**

In [411]:
def data_cleaning(df):    
    object_cols = df.select_dtypes("object")
    df[object_cols.columns] = object_cols.fillna("Unknown")

    numeric_cols = df.select_dtypes("number")
    df[numeric_cols.columns] = numeric_cols.fillna(numeric_cols.median())
    return df
df = data_cleaning(df)

C:\Users\Tonmoy Saha\AppData\Local\Temp\ipykernel_44328\3461225569.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes("object")

Results below show that
- "Country" column is mostly one single category making it ideal for a binary column.
- The other two columns are well distributed among the top 5 categories dominating most of the data indicating that all 5 categories should be preserved.

All other categories of each column will be categorized as "Other".

**Changing all other categories to "Other" for "Country" column except unknown values.**

In [412]:
df["Country"] = list(map(lambda x: x if (x=="India" or x=="Unknown") else "Other",df["Country"]))
df["Country"].value_counts()

Country
India      6492
Unknown    2461
Other       287
Name: count, dtype: int64

**Below we checked the porportion of data for top 5 categories for each high cardinality column to ensure which method to approach to reduce cardinality.**

In [413]:
high_cardinality = ["Country","Tags","Lead Source","Specialization","Last Activity"]
def card_check(df,card,top_n=5):
    for col in card:
        print(df[col].value_counts(normalize=True).head(top_n)*100)
        print("\n")
card_check(df,high_cardinality)

Country
India      70.259740
Unknown    26.634199
Other       3.106061
Name: proportion, dtype: float64


Tags
Unknown                                36.287879
Will revert after reading the email    22.424242
Ringing                                13.019481
Interested in other courses             5.551948
Already a student                       5.032468
Name: proportion, dtype: float64


Lead Source
Google            31.038961
Direct Traffic    27.521645
Olark Chat        18.993506
Organic Search    12.489177
Reference          5.779221
Name: proportion, dtype: float64


Specialization
Unknown                      36.580087
Finance Management           10.562771
Human Resource Management     9.177489
Marketing Management          9.069264
Operations Management         5.443723
Name: proportion, dtype: float64


Last Activity
Email Opened               37.196970
SMS Sent                   29.707792
Olark Chat Conversation    10.530303
Page Visited on Website     6.926407
Converted to Lead           4.632035
Name: proportion, dtype: float64

**Changing other high cardinality columns to 6 distinct categories only.**

In [414]:
def reduce_cardinality(df,cols):
    for col in cols:
        other_cat = df[col].value_counts(ascending=True)[0:-5]
        df[col] = list(map(lambda x: "Other" if x in other_cat else x,df[col]))
    return df
df = reduce_cardinality(df,high_cardinality[1:])
card_check(df,high_cardinality,6)

Country
India      70.259740
Unknown    26.634199
Other       3.106061
Name: proportion, dtype: float64


Tags
Unknown                                36.287879
Will revert after reading the email    22.424242
Other                                  17.683983
Ringing                                13.019481
Interested in other courses             5.551948
Already a student                       5.032468
Name: proportion, dtype: float64


Lead Source
Google            31.038961
Direct Traffic    27.521645
Olark Chat        18.993506
Organic Search    12.489177
Reference          5.779221
Other              4.177489
Name: proportion, dtype: float64


Specialization
Unknown                      36.580087
Other                        29.166667
Finance Management           10.562771
Human Resource Management     9.177489
Marketing Management          9.069264
Operations Management         5.443723
Name: proportion, dtype: float64


Last Activity
Email Opened               37.196970
SMS Sent                   29.707792
Other                      11.006494
Olark Chat Conversation    10.530303
Page Visited on Website     6.926407
Converted to Lead           4.632035
Name: proportion, dtype: float64

In [415]:
df.to_csv("data/Cleaned_Leads.csv",index=False)